version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: SonarAnalyzer.CSharp
    versions:
    - 8.17.0.26580
