language: csharp

solution: Vika.sln

install:
  - nuget restore Vika.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release Vika.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./NVika.Tests/bin/Release/NVika.Tests.dll