configuration: Release

install:
- choco install GitVersion
- choco install opencover -source https://nuget.org/api/v2/
- choco install coveralls.io -source https://nuget.org/api/v2/
- choco install resharper-clt
- GitVersion /output buildserver /UpdateAssemblyInfo true

cache:
- packages -> **\packages.config
- C:\ProgramData\chocolatey\bin\OpenCover.Console.exe -> appveyor.yml
- C:\ProgramData\chocolatey\bin\coveralls.net.exe -> appveyor.yml
- C:\ProgramData\chocolatey\bin\GitVersion.exe -> appveyor.yml
- C:\ProgramData\chocolatey\bin\inspectcode.exe -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml

#environment:
#  COVERALLS_REPO_TOKEN:
#    secure: GdZUBHY15XkHS4bAvE7K42B4ssrtz19qK20fSnDUvjlFDbIUXNUDop6qmx8N+GQn

#before_build:
#  - nuget restore

#build:
#  project: Vika.sln
#  verbosity: minimal

#after_build:
#- inspectcode /o="inspectcodereport.xml" "Vika.sln"
#"- NVika\bin\Release\NVika buildserver "inspectcodereport.xml" --debug --includesource

#test_script:
#- OpenCover.Console.exe -register:user -filter:"+[NVika]*" -excludebyattribute:"*.ExcludeFromCodeCoverage" -target:"xunit.console.clr4.exe" -targetargs:"""NVika.Tests\bin\Release\NVika.Tests.dll"" /noshadow /appveyor" -output:coverage.xml -returntargetcode
#- coveralls.net --opencover coverage.xml

#artifacts:
#- path: coverage.xml
#- path: NVika\bin\Release\NVika.exe.CodeAnalysisLog.xml
#  name: NVika.exe.CodeAnalysisLog.xml
