cache:
- src/packages -> **\packages.config
- C:\ProgramData\chocolatey\bin -> build.fsx
- C:\ProgramData\chocolatey\lib -> build.fsx
- tools -> build.fsx

install:
- GitVersion /output buildserver /UpdateAssemblyInfo true

environment:
  COVERALLS_REPO_TOKEN:
    secure: GdZUBHY15XkHS4bAvE7K42B4ssrtz19qK20fSnDUvjlFDbIUXNUDop6qmx8N+GQn

build_script:
  build.bat

test: off

artifacts:
- path: artifacts\coverage.xml

- path: build\NVika.exe.CodeAnalysisLog.xml
  name: NVika.exe.CodeAnalysisLog.xml

- path: artifacts\inspectcodereport.xml

- path: artifacts\ReleaseNotes.html

- path: artifacts\NVika.*.zip
  name: NVika.zip

- path: artifacts\nvika.*.nupkg
  name: NVika.nupkg
  
- path: artifacts\NVikaHelper.fsx
  name: NVikaHelper.fsx

deploy:
  - provider: GitHub
    auth_token:
      secure: WaNF2IUzat+PQQqquLoaN43QIpnUsrYgSOGN3P5Tpy+A+ANOWQqvWE0eFA+XwmmX
    artifact: NVika.zip, NVikaHelper.fsx
    description: $(SemanticReleaseNotes)
    on:
      appveyor_repo_tag: true

  - provider: NuGet
    server: https://chocolatey.org/
    api_key:
      secure: 2GBJF71EQfU+kIL5NHVM4wYoCRcFf/gM/voNIgud8vDWUE+uA1ye/hRWjJPQWA5w
    skip_symbols: true
    artifact: NVika.nupkg
    on:
      appveyor_repo_tag: true