configuration: Release

install:
- GitVersion /output buildserver /UpdateAssemblyInfo true
- choco install opencover -source https://nuget.org/api/v2/
- choco install coveralls.io -source https://nuget.org/api/v2/
- choco install resharper-clt

cache:
- packages -> **\packages.config
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  COVERALLS_REPO_TOKEN:
    secure: GdZUBHY15XkHS4bAvE7K42B4ssrtz19qK20fSnDUvjlFDbIUXNUDop6qmx8N+GQn

before_build:
  - nuget restore src\Vika.sln

build:
  project: src\Vika.sln
  verbosity: minimal

after_build:
- inspectcode /o="inspectcodereport.xml" /project="NVika" "Vika.sln"
- NVika\bin\Release\NVika parsereport "inspectcodereport.xml" --debug --includesource
- tools\SemanticReleaseNotesParser.exe -g Categories -t File -r ReleaseNotes.md --debug
- tools\SemanticReleaseNotesParser.exe -g Categories -t Environment -f Markdown -r ReleaseNotes.md --debug
# build chocolatey package
- ps: (gc PackagingAssets\chocolatey\tools\chocolateyInstall.ps1).replace('{{version}}', $env:GitVersion_NuGetVersion).replace('{{tag}}',$env:appveyor_repo_tag_name)|sc PackagingAssets\chocolatey\tools\chocolateyInstall.ps1
- choco pack PackagingAssets\chocolatey\NVika.nuspec --version %GitVersion_NuGetVersion%
# zip for github package
- 7z a NVika.%GitVersion_NuGetVersion%.zip %appveyor_build_folder%\NVika\bin\Release\*.dll
- 7z a NVika.%GitVersion_NuGetVersion%.zip %appveyor_build_folder%\NVika\bin\Release\NVika.exe
- 7z a NVika.%GitVersion_NuGetVersion%.zip ReleaseNotes.html

test_script:
- OpenCover.Console.exe -register:user -filter:"+[NVika]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -target:"%xunit20%\xunit.console.exe" -targetargs:"""NVika.Tests\bin\Release\NVika.Tests.dll"" -noshadow -appveyor" -output:coverage.xml -returntargetcode
- coveralls.net --opencover coverage.xml

artifacts:
- path: coverage.xml

- path: NVika\bin\Release\NVika.exe.CodeAnalysisLog.xml
  name: NVika.exe.CodeAnalysisLog.xml

- path: inspectcodereport.xml

- path: ReleaseNotes.html

- path: NVika.*.zip
  name: NVika.zip

- path: nvika.*.nupkg
  name: NVika.nupkg

deploy:
  - provider: GitHub
    auth_token:
      secure: WaNF2IUzat+PQQqquLoaN43QIpnUsrYgSOGN3P5Tpy+A+ANOWQqvWE0eFA+XwmmX
    artifact: NVika.zip
    description: $(SemanticReleaseNotes)
    on:
      appveyor_repo_tag: true

  - provider: NuGet
    server: https://chocolatey.org/
    api_key:
      secure: 2GBJF71EQfU+kIL5NHVM4wYoCRcFf/gM/voNIgud8vDWUE+uA1ye/hRWjJPQWA5w
    skip_symbols: true
    artifact: NVika.nupkg
    on:
      appveyor_repo_tag: true